version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://neondb_owner:npg_8oFNVLmjn1CU@ep-delicate-snowflake-ac7c8wwt-pooler.sa-east-1.aws.neon.tech/vertexdb?sslmode=require
    # Si querés usar .env.docker también dentro del contenedor en tiempo de ejecución:
    env_file:
      - .env.docker
    networks:
      - vertex-network
volumes:
  pgdata:

networks:
  vertex-network:
    driver: bridge
